### ISSUE TITLE
multiple arguments to daemon process are not supported

### ISSUE THREAD

**Issue by weisjohn** [niegowski/node-daemonize2#10]
In the options, it specifies that during setup, you can specify _arguments_

`args` - additional node runtime arguments, ie `--debug`

If I specify `--expose_gc --max_executable_size=10`, in my code `typeof gc` returns `function`

But, if I specify `--expose_gc --max_executable_size=10`, `typeof gc` returns `undefined` in my daemon.

I believe when you pass a string with spaces through `spawn`, the process doesn't get them as separate arguments, but rather as one argument.  

As I need this functionality for my own use, I'm forking to get it today.  Proposed functionality:

You can now specify args as an array or string. 

Let me know if I should submit a pull request.

**Comment by niegowski** [comment]
resolved with dc1c7fbf36f8044bbe7b723de41c11ff7c829e01

**Comment by weisjohn** [comment]
Thanks for fixing.
