### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by neilstuartcraig** [niegowski/node-daemonize2#2]
Hi (again)

Thanks again for daemonize2, it fits perfectly with what I need.

I just wondered if it's possible to add a callback to the start and stop methods, would be very helpful.

Cheers
Neil

**Comment by niegowski** [comment]
Hi, 

I'm happy that you like daemonize2.

I'm not sure what you are asking for. Is it sth like this?:

``` js
daemon.start(function() { });
daemon.stop(function() { });
```

You can write it now like this:

``` js
daemon.start().once("started", function() { });
daemon.stop().once("stopped", function() { });
```

I can add the first way as an alias for the second one.

**Comment by neilstuartcraig** [comment]
Hi

sorry for the slow reply...

Yes, that's exactly what i'd like. The initial reason for wanting it was to allow a simple method to restart the app as you'd get in most init scripts. The alias sounds great if thats possible.

Many thanks
Neil

**Comment by niegowski** [comment]
Hi,

Check latest version :-)

Kuba

**Comment by niegowski** [comment]
Just added error handling in start/stop callbacks.

Kuba

**Comment by neilstuartcraig** [comment]
Hi Kuba

Sorry for the slow reply, I have been away with work.

That's great, many thanks - I actually implemented as per your original method which worked perfectly but I will update my NPM and use the callback.

Once my app is finished, i'll open source it and let you know. It's a pretty flexible HTTP redirector which is designed to be easy to configure and (hopefully) very fast. My reason for creating it is that our current redirector at work is very old and nasty, it does deal with several million requests per day but I am confident node is a better fit and it's now demonised and clustered so it should be a winner!

Thanks again, it's a great module you've created - took about 2 minutes to implement :-).

Cheers
Neil

**Comment by neilstuartcraig** [comment]
Hello again Kuba

I have updated to rc4 and my app is now working well, i have used your callbacks to implement a restart daemon method which works well.

The issue i have right now is that my app (an http redirector) won't bind to the port i specify when in demonised mode and using node cluster, without either of those it works fine. I am sure this is a problem of my making but i am having problems debugging when demonised because console.log isn't working from forked processes running under the daemon. I wondered if you had any pointers which might help be to get console.log working?

Any help would be very much appreciated.

My app is at: https://github.com/neilstuartcraig/tdp-http-redirector

Thanks again
Neil

**Comment by niegowski** [comment]
Hi

You could write logs to some file like in example in daemonize: https://github.com/niegowski/node-daemonize2/blob/master/examples/advanced/app.js

Also you should handle uncaughtException ie like this: https://github.com/niegowski/node-daemonize2/blob/master/examples/advanced/app.js#L41-43

Cheers
Kuba

**Comment by niegowski** [comment]
Hello again

I looked at making clusters with daemonize and it appeared that cluster uses process.argv to fork workers. 
Daemonize was messing with it and now I fixed it with rc.5

Greetings
Kuba

**Comment by neilstuartcraig** [comment]
Hello again Kuba

That' great, i updated and tested with rc.5 and it's working nicely - really appreciate it.

I'll look at your suggestions for log writing and exceptions too - this is the first thing i have written in nodejs so it's early days for me but it seems to work quite nicely so i'll carry on improving it over time.

Thanks again for all your help and daemonize2
Neil

**Comment by niegowski** [comment]
Thanks for reporting an issue :-)

Greetings
Kuba
